"""
AI Model and Configuration Version Tracking System.

Defines immutable version bundle metadata, model compatibility validators,
and migration management for facial recognition components.
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)


class IncompatibleEmbeddingModelError(ValueError):
    """Raised when attempting to compare embeddings generated by incompatible models or dimensions."""
    pass


@dataclass(frozen=True)
class ModelConfigVersionBundle:
    """
    Immutable snapshot of all AI models and configuration versions
    that materially affect a facial recognition decision.
    """
    detection_model_version: str = "scrfd_500m_bnkps_v1"
    embedding_model_version: str = "w600k_mbf_v1"
    gallery_version: int = 1
    threshold_version: int = 1
    camera_config_version: int = 1
    algorithm_version: str = "temporal_fusion_v2"

    @property
    def bundle_hash(self) -> str:
        """Deterministic SHA-256 fingerprint of the complete configuration bundle."""
        payload = {
            "detection_model_version": self.detection_model_version,
            "embedding_model_version": self.embedding_model_version,
            "gallery_version": self.gallery_version,
            "threshold_version": self.threshold_version,
            "camera_config_version": self.camera_config_version,
            "algorithm_version": self.algorithm_version,
        }
        serialized = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "detection_model_version": self.detection_model_version,
            "embedding_model_version": self.embedding_model_version,
            "gallery_version": self.gallery_version,
            "threshold_version": self.threshold_version,
            "camera_config_version": self.camera_config_version,
            "algorithm_version": self.algorithm_version,
            "bundle_hash": self.bundle_hash,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> ModelConfigVersionBundle:
        return cls(
            detection_model_version=str(data.get("detection_model_version", "scrfd_500m_bnkps_v1")),
            embedding_model_version=str(data.get("embedding_model_version", "w600k_mbf_v1")),
            gallery_version=int(data.get("gallery_version", 1)),
            threshold_version=int(data.get("threshold_version", 1)),
            camera_config_version=int(data.get("camera_config_version", 1)),
            algorithm_version=str(data.get("algorithm_version", "temporal_fusion_v2")),
        )


class EmbeddingVersionValidator:
    """
    Validates model compatibility to strictly prevent silent false matches
    from comparing vectors generated by different backbone architectures.
    """

    # Registered embedding dimensions per model
    KNOWN_MODEL_DIMENSIONS: Dict[str, int] = {
        "w600k_mbf_v1": 512,
        "w600k_r50_v1": 512,
        "arcface_r100_v1": 512,
        "mobilenet_v2_256": 256,
        "buffalo_s": 512,
        "buffalo_l": 512,
    }

    # Compatibility groups (models within the same group share identical metric space)
    COMPATIBILITY_GROUPS: Dict[str, str] = {
        "w600k_mbf_v1": "insightface_w600k",
        "buffalo_s": "insightface_w600k",
        "w600k_r50_v1": "insightface_w600k_r50",
        "arcface_r100_v1": "arcface_r100",
        "mobilenet_v2_256": "mobilenet_256",
    }

    @classmethod
    def are_compatible(
        cls,
        model_a: str,
        model_b: str,
        dim_a: Optional[int] = None,
        dim_b: Optional[int] = None,
    ) -> bool:
        """Check if two embedding models are mathematically compatible for comparison."""
        if model_a == model_b:
            if dim_a is not None and dim_b is not None and dim_a != dim_b:
                return False
            return True

        # Check compatibility group
        group_a = cls.COMPATIBILITY_GROUPS.get(model_a)
        group_b = cls.COMPATIBILITY_GROUPS.get(model_b)
        if group_a and group_b and group_a == group_b:
            if dim_a is not None and dim_b is not None and dim_a != dim_b:
                return False
            return True

        return False

    @classmethod
    def validate_comparison(
        cls,
        query_model: str,
        gallery_model: str,
        query_dim: Optional[int] = None,
        gallery_dim: Optional[int] = None,
    ) -> None:
        """
        Validate compatibility before vector comparison.
        
        Raises:
            IncompatibleEmbeddingModelError: If models or dimensions are mismatched.
        """
        if not cls.are_compatible(query_model, gallery_model, query_dim, gallery_dim):
            raise IncompatibleEmbeddingModelError(
                f"Embedding model mismatch: cannot compare query embedding from '{query_model}' "
                f"(dim={query_dim or 'unknown'}) with gallery embedding from '{gallery_model}' "
                f"(dim={gallery_dim or 'unknown'}). Cross-model vector comparison produces invalid similarity scores."
            )


class ModelMigrationManager:
    """
    Manages multi-model transitions and dual-embedding operations during rolling upgrades.
    """

    def __init__(self) -> None:
        self.active_embedding_models: Set[str] = {"w600k_mbf_v1"}
        self.deprecated_models: Set[str] = set()

    def register_migration_target(self, new_model_version: str) -> None:
        """Allow a new model version alongside the current model during rolling upgrade."""
        self.active_embedding_models.add(new_model_version)
        logger.info(f"Registered migration target model: {new_model_version}")

    def deprecate_model(self, old_model_version: str) -> None:
        """Mark an older model version as deprecated."""
        self.deprecated_models.add(old_model_version)
        logger.info(f"Deprecated model version: {old_model_version}")

    def is_model_supported(self, model_version: str) -> bool:
        """Check if an embedding model is currently accepted by the system."""
        return model_version in self.active_embedding_models or model_version not in self.deprecated_models
