"""add idempotency and tracking columns

Revision ID: 872c138c1f7e
Revises: 0001_initial_schema
Create Date: 2026-09-23 10:00:40.802526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872c138c1f7e'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unregistered_subjects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('representative_embedding', models.Vector(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unregistered_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unregistered_subjects_id'), ['id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('camera_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_transitions_detected_at'), ['detected_at'], unique=False)

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_name'))

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unregistered_subject_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding_vector', models.Vector(), nullable=True))
        batch_op.create_index(batch_op.f('ix_detections_config_version'), ['config_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_embedding_model_version'), ['embedding_model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_unregistered_subject_id'), ['unregistered_subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_version_bundle_hash'), ['version_bundle_hash'], unique=False)
        batch_op.create_foreign_key(None, 'unregistered_subjects', ['unregistered_subject_id'], ['id'])

    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('employee', 'vip', 'visitor', 'blacklist', 'watchlist', name='profilerole'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('employee', 'vip', 'visitor', 'blacklist', 'watchlist', name='profilerole'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_detections_version_bundle_hash'))
        batch_op.drop_index(batch_op.f('ix_detections_unregistered_subject_id'))
        batch_op.drop_index(batch_op.f('ix_detections_embedding_model_version'))
        batch_op.drop_index(batch_op.f('ix_detections_config_version'))
        batch_op.drop_column('embedding_vector')
        batch_op.drop_column('unregistered_subject_id')

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_name'), ['name'], unique=False)

    with op.batch_alter_table('camera_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_transitions_detected_at'))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))

    with op.batch_alter_table('unregistered_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unregistered_subjects_id'))

    op.drop_table('unregistered_subjects')
    # ### end Alembic commands ###
