import type {
  Alert,
  AttendanceRecord,
  Camera,
  DemographicSlice,
  DuplicateCandidate,
  FaceLog,
  FootfallBucket,
  ForensicMatch,
  ModelThresholds,
  Profile,
  SubjectTrajectory,
  SystemKpis,
  UnknownCapture,
} from './types'

/*
 * Deterministic mock dataset so the UI renders identically on server and
 * client (no hydration drift) and works with zero backend connectivity.
 */

const DAY = '2026-08-11'
const tones = ['sky', 'amber', 'rose', 'violet', 'emerald', 'cyan', 'orange', 'indigo']
const tone = (i: number) => tones[i % tones.length]

function iso(hour: number, minute: number, second = 0) {
  const h = String(hour).padStart(2, '0')
  const m = String(minute).padStart(2, '0')
  const s = String(second).padStart(2, '0')
  return `${DAY}T${h}:${m}:${s}`
}

// --- Cameras ---------------------------------------------------------------

export const cameras: Camera[] = [
  {
    id: 'CAM-01',
    name: 'Main Lobby',
    zone: 'Entrance',
    ipAddress: '10.4.12.11',
    rtspUrl: 'rtsp://10.4.12.11:554/stream1',
    status: 'online',
    pingMs: 12,
    frameLatencyMs: 41,
    fps: 24,
    gpuLoad: 62,
    cpuLoad: 38,
    lastHeartbeat: iso(10, 42, 3),
    detectionsToday: 1284,
  },
  {
    id: 'CAM-02',
    name: 'North Corridor',
    zone: 'Floor 2',
    ipAddress: '10.4.12.12',
    rtspUrl: 'rtsp://10.4.12.12:554/stream1',
    status: 'online',
    pingMs: 18,
    frameLatencyMs: 55,
    fps: 22,
    gpuLoad: 71,
    cpuLoad: 44,
    lastHeartbeat: iso(10, 42, 1),
    detectionsToday: 968,
  },
  {
    id: 'CAM-03',
    name: 'Server Room',
    zone: 'Restricted',
    ipAddress: '10.4.12.13',
    rtspUrl: 'rtsp://10.4.12.13:554/stream1',
    status: 'degraded',
    pingMs: 47,
    frameLatencyMs: 128,
    fps: 11,
    gpuLoad: 88,
    cpuLoad: 79,
    lastHeartbeat: iso(10, 41, 52),
    detectionsToday: 214,
  },
  {
    id: 'CAM-04',
    name: 'East Stairwell',
    zone: 'Floor 3',
    ipAddress: '10.4.12.14',
    rtspUrl: 'rtsp://10.4.12.14:554/stream1',
    status: 'online',
    pingMs: 15,
    frameLatencyMs: 48,
    fps: 23,
    gpuLoad: 58,
    cpuLoad: 35,
    lastHeartbeat: iso(10, 42, 2),
    detectionsToday: 742,
  },
  {
    id: 'CAM-05',
    name: 'Parking Deck',
    zone: 'Perimeter',
    ipAddress: '10.4.12.15',
    rtspUrl: 'rtsp://10.4.12.15:554/stream1',
    status: 'online',
    pingMs: 22,
    frameLatencyMs: 63,
    fps: 20,
    gpuLoad: 66,
    cpuLoad: 41,
    lastHeartbeat: iso(10, 42, 0),
    detectionsToday: 531,
  },
  {
    id: 'CAM-06',
    name: 'Loading Bay',
    zone: 'Perimeter',
    ipAddress: '10.4.12.16',
    rtspUrl: 'rtsp://10.4.12.16:554/stream1',
    status: 'offline',
    pingMs: 0,
    frameLatencyMs: 0,
    fps: 0,
    gpuLoad: 0,
    cpuLoad: 0,
    lastHeartbeat: iso(9, 58, 14),
    detectionsToday: 96,
  },
  {
    id: 'CAM-07',
    name: 'Cafeteria',
    zone: 'Floor 1',
    ipAddress: '10.4.12.17',
    rtspUrl: 'rtsp://10.4.12.17:554/stream1',
    status: 'online',
    pingMs: 14,
    frameLatencyMs: 44,
    fps: 24,
    gpuLoad: 60,
    cpuLoad: 37,
    lastHeartbeat: iso(10, 42, 3),
    detectionsToday: 1103,
  },
  {
    id: 'CAM-08',
    name: 'Rear Exit',
    zone: 'Perimeter',
    ipAddress: '10.4.12.18',
    rtspUrl: 'rtsp://10.4.12.18:554/stream1',
    status: 'online',
    pingMs: 19,
    frameLatencyMs: 51,
    fps: 22,
    gpuLoad: 63,
    cpuLoad: 39,
    lastHeartbeat: iso(10, 42, 1),
    detectionsToday: 388,
  },
]

// --- Profiles --------------------------------------------------------------

export const profiles: Profile[] = [
  {
    id: 'PRF-1001',
    name: 'Aria Chen',
    role: 'employee',
    department: 'Engineering',
    embeddingStatus: 'indexed',
    embeddingCount: 6,
    enrolledAt: '2025-11-02',
    lastSeen: iso(10, 15),
    age: 31,
    gender: 'female',
    avatarTone: 'sky',
  },
  {
    id: 'PRF-1002',
    name: 'Marcus Webb',
    role: 'employee',
    department: 'Facilities',
    embeddingStatus: 'indexed',
    embeddingCount: 5,
    enrolledAt: '2025-09-18',
    lastSeen: iso(10, 22),
    age: 45,
    gender: 'male',
    avatarTone: 'emerald',
  },
  {
    id: 'PRF-1003',
    name: 'Dr. Lena Ortiz',
    role: 'vip',
    department: 'Board',
    embeddingStatus: 'indexed',
    embeddingCount: 8,
    enrolledAt: '2025-06-30',
    lastSeen: iso(9, 47),
    age: 52,
    gender: 'female',
    avatarTone: 'violet',
    notes: 'Executive escort protocol required.',
  },
  {
    id: 'PRF-1004',
    name: 'Kofi Mensah',
    role: 'employee',
    department: 'Security',
    embeddingStatus: 'indexed',
    embeddingCount: 7,
    enrolledAt: '2025-03-12',
    lastSeen: iso(10, 38),
    age: 38,
    gender: 'male',
    avatarTone: 'amber',
  },
  {
    id: 'PRF-1005',
    name: 'Subject 0x8F (BOLO)',
    role: 'blacklist',
    department: '—',
    embeddingStatus: 'indexed',
    embeddingCount: 3,
    enrolledAt: '2026-01-20',
    lastSeen: iso(10, 31),
    age: 40,
    gender: 'male',
    avatarTone: 'rose',
    notes: 'Trespass order active. Notify duty officer on sight.',
  },
  {
    id: 'PRF-1006',
    name: 'Priya Nair',
    role: 'vip',
    department: 'Investor Relations',
    embeddingStatus: 'pending',
    embeddingCount: 2,
    enrolledAt: '2026-08-04',
    lastSeen: null,
    age: 36,
    gender: 'female',
    avatarTone: 'cyan',
  },
  {
    id: 'PRF-1007',
    name: 'Tomasz Wójcik',
    role: 'watchlist',
    department: '—',
    embeddingStatus: 'stale',
    embeddingCount: 4,
    enrolledAt: '2025-12-11',
    lastSeen: iso(8, 12),
    age: 29,
    gender: 'male',
    avatarTone: 'orange',
    notes: 'Flagged pending investigation.',
  },
  {
    id: 'PRF-1008',
    name: 'Hana Suzuki',
    role: 'employee',
    department: 'Design',
    embeddingStatus: 'indexed',
    embeddingCount: 5,
    enrolledAt: '2025-07-22',
    lastSeen: iso(10, 5),
    age: 27,
    gender: 'female',
    avatarTone: 'indigo',
  },
  {
    id: 'PRF-1009',
    name: 'Guest Contractor',
    role: 'visitor',
    department: 'Vendor',
    embeddingStatus: 'missing',
    embeddingCount: 0,
    enrolledAt: '2026-08-11',
    lastSeen: iso(10, 40),
    age: 34,
    gender: 'male',
    avatarTone: 'sky',
  },
  {
    id: 'PRF-1010',
    name: 'Elena Rossi',
    role: 'employee',
    department: 'Engineering',
    embeddingStatus: 'indexed',
    embeddingCount: 6,
    enrolledAt: '2025-10-09',
    lastSeen: iso(9, 58),
    age: 33,
    gender: 'female',
    avatarTone: 'emerald',
  },
]

// --- Face logs -------------------------------------------------------------

const roleOf = (id: string | null) =>
  profiles.find((p) => p.id === id)?.role ?? null

export const faceLogs: FaceLog[] = [
  {
    id: 'LOG-90311',
    cameraId: 'CAM-01',
    cameraName: 'Main Lobby',
    timestamp: iso(10, 41, 12),
    status: 'flagged',
    confidence: 97.4,
    livenessScore: 92,
    profileId: 'PRF-1005',
    profileName: 'Subject 0x8F (BOLO)',
    role: 'blacklist',
    age: 40,
    gender: 'male',
    wearingMask: false,
    wearingGlasses: true,
    snapshotTone: 'rose',
  },
  {
    id: 'LOG-90310',
    cameraId: 'CAM-04',
    cameraName: 'East Stairwell',
    timestamp: iso(10, 38, 47),
    status: 'recognized',
    confidence: 98.9,
    livenessScore: 96,
    profileId: 'PRF-1004',
    profileName: 'Kofi Mensah',
    role: 'employee',
    age: 38,
    gender: 'male',
    wearingMask: false,
    wearingGlasses: false,
    snapshotTone: 'amber',
  },
  {
    id: 'LOG-90309',
    cameraId: 'CAM-02',
    cameraName: 'North Corridor',
    timestamp: iso(10, 36, 3),
    status: 'unknown',
    confidence: 41.2,
    livenessScore: 71,
    profileId: null,
    profileName: null,
    role: null,
    age: 24,
    gender: 'female',
    wearingMask: true,
    wearingGlasses: false,
    snapshotTone: 'cyan',
  },
  {
    id: 'LOG-90308',
    cameraId: 'CAM-01',
    cameraName: 'Main Lobby',
    timestamp: iso(10, 31, 55),
    status: 'flagged',
    confidence: 88.1,
    livenessScore: 84,
    profileId: 'PRF-1007',
    profileName: 'Tomasz Wójcik',
    role: 'watchlist',
    age: 29,
    gender: 'male',
    wearingMask: false,
    wearingGlasses: false,
    snapshotTone: 'orange',
  },
  {
    id: 'LOG-90307',
    cameraId: 'CAM-07',
    cameraName: 'Cafeteria',
    timestamp: iso(10, 22, 18),
    status: 'recognized',
    confidence: 96.3,
    livenessScore: 94,
    profileId: 'PRF-1002',
    profileName: 'Marcus Webb',
    role: 'employee',
    age: 45,
    gender: 'male',
    wearingMask: false,
    wearingGlasses: true,
    snapshotTone: 'emerald',
  },
  {
    id: 'LOG-90306',
    cameraId: 'CAM-01',
    cameraName: 'Main Lobby',
    timestamp: iso(10, 15, 9),
    status: 'recognized',
    confidence: 99.1,
    livenessScore: 97,
    profileId: 'PRF-1001',
    profileName: 'Aria Chen',
    role: 'employee',
    age: 31,
    gender: 'female',
    wearingMask: false,
    wearingGlasses: false,
    snapshotTone: 'sky',
  },
  {
    id: 'LOG-90305',
    cameraId: 'CAM-05',
    cameraName: 'Parking Deck',
    timestamp: iso(10, 9, 41),
    status: 'unknown',
    confidence: 33.7,
    livenessScore: 62,
    profileId: null,
    profileName: null,
    role: null,
    age: 51,
    gender: 'male',
    wearingMask: true,
    wearingGlasses: true,
    snapshotTone: 'violet',
  },
  {
    id: 'LOG-90304',
    cameraId: 'CAM-07',
    cameraName: 'Cafeteria',
    timestamp: iso(10, 5, 22),
    status: 'recognized',
    confidence: 95.7,
    livenessScore: 93,
    profileId: 'PRF-1008',
    profileName: 'Hana Suzuki',
    role: 'employee',
    age: 27,
    gender: 'female',
    wearingMask: false,
    wearingGlasses: false,
    snapshotTone: 'indigo',
  },
  {
    id: 'LOG-90303',
    cameraId: 'CAM-02',
    cameraName: 'North Corridor',
    timestamp: iso(9, 58, 12),
    status: 'recognized',
    confidence: 94.2,
    livenessScore: 90,
    profileId: 'PRF-1010',
    profileName: 'Elena Rossi',
    role: 'employee',
    age: 33,
    gender: 'female',
    wearingMask: false,
    wearingGlasses: true,
    snapshotTone: 'emerald',
  },
  {
    id: 'LOG-90302',
    cameraId: 'CAM-04',
    cameraName: 'East Stairwell',
    timestamp: iso(9, 47, 33),
    status: 'recognized',
    confidence: 97.8,
    livenessScore: 95,
    profileId: 'PRF-1003',
    profileName: 'Dr. Lena Ortiz',
    role: 'vip',
    age: 52,
    gender: 'female',
    wearingMask: false,
    wearingGlasses: true,
    snapshotTone: 'violet',
  },
  {
    id: 'LOG-90301',
    cameraId: 'CAM-08',
    cameraName: 'Rear Exit',
    timestamp: iso(9, 39, 2),
    status: 'unknown',
    confidence: 38.5,
    livenessScore: 55,
    profileId: null,
    profileName: null,
    role: null,
    age: 22,
    gender: 'female',
    wearingMask: false,
    wearingGlasses: false,
    snapshotTone: 'rose',
  },
  {
    id: 'LOG-90300',
    cameraId: 'CAM-07',
    cameraName: 'Cafeteria',
    timestamp: iso(9, 31, 47),
    status: 'recognized',
    confidence: 93.4,
    livenessScore: 89,
    profileId: 'PRF-1009',
    profileName: 'Guest Contractor',
    role: 'visitor',
    age: 34,
    gender: 'male',
    wearingMask: false,
    wearingGlasses: false,
    snapshotTone: 'sky',
  },
]

// Expand the log volume a bit so pagination is meaningful.
const extraLogs: FaceLog[] = Array.from({ length: 24 }, (_, i) => {
  const base = faceLogs[i % faceLogs.length]
  const minute = 28 - i
  return {
    ...base,
    id: `LOG-902${String(76 - i).padStart(2, '0')}`,
    timestamp: iso(9, Math.max(0, minute), (i * 7) % 60),
    role: roleOf(base.profileId),
  }
})

export const allFaceLogs: FaceLog[] = [...faceLogs, ...extraLogs]

// --- Alerts ----------------------------------------------------------------

export const alerts: Alert[] = [
  {
    id: 'ALT-5501',
    logId: 'LOG-90311',
    cameraId: 'CAM-01',
    cameraName: 'Main Lobby',
    timestamp: iso(10, 41, 12),
    severity: 'critical',
    reason: 'Blacklist / BOLO match at controlled entrance',
    profileId: 'PRF-1005',
    profileName: 'Subject 0x8F (BOLO)',
    role: 'blacklist',
    confidence: 97.4,
    acknowledged: false,
    snapshotTone: 'rose',
  },
  {
    id: 'ALT-5500',
    logId: 'LOG-90308',
    cameraId: 'CAM-01',
    cameraName: 'Main Lobby',
    timestamp: iso(10, 31, 55),
    severity: 'high',
    reason: 'Watchlist subject entered monitored zone',
    profileId: 'PRF-1007',
    profileName: 'Tomasz Wójcik',
    role: 'watchlist',
    confidence: 88.1,
    acknowledged: false,
    snapshotTone: 'orange',
  },
  {
    id: 'ALT-5499',
    logId: 'LOG-90305',
    cameraId: 'CAM-05',
    cameraName: 'Parking Deck',
    timestamp: iso(10, 9, 41),
    severity: 'medium',
    reason: 'Low liveness score — possible spoof attempt',
    profileId: null,
    profileName: 'Unidentified subject',
    role: 'watchlist',
    confidence: 33.7,
    acknowledged: false,
    snapshotTone: 'violet',
  },
  {
    id: 'ALT-5498',
    logId: 'LOG-90301',
    cameraId: 'CAM-08',
    cameraName: 'Rear Exit',
    timestamp: iso(9, 39, 2),
    severity: 'medium',
    reason: 'Repeated unknown face at perimeter exit',
    profileId: null,
    profileName: 'Unidentified subject',
    role: 'watchlist',
    confidence: 38.5,
    acknowledged: true,
    snapshotTone: 'rose',
  },
]

// --- Unknown captures ------------------------------------------------------

export const unknownCaptures: UnknownCapture[] = [
  {
    id: 'UNK-3301',
    cameraId: 'CAM-02',
    cameraName: 'North Corridor',
    timestamp: iso(10, 36, 3),
    confidence: 41.2,
    livenessScore: 71,
    age: 24,
    gender: 'female',
    snapshotTone: 'cyan',
  },
  {
    id: 'UNK-3302',
    cameraId: 'CAM-05',
    cameraName: 'Parking Deck',
    timestamp: iso(10, 9, 41),
    confidence: 33.7,
    livenessScore: 62,
    age: 51,
    gender: 'male',
    snapshotTone: 'violet',
  },
  {
    id: 'UNK-3303',
    cameraId: 'CAM-08',
    cameraName: 'Rear Exit',
    timestamp: iso(9, 39, 2),
    confidence: 38.5,
    livenessScore: 55,
    age: 22,
    gender: 'female',
    snapshotTone: 'rose',
  },
  {
    id: 'UNK-3304',
    cameraId: 'CAM-03',
    cameraName: 'Server Room',
    timestamp: iso(9, 21, 8),
    confidence: 44.9,
    livenessScore: 68,
    age: 37,
    gender: 'male',
    snapshotTone: 'amber',
  },
  {
    id: 'UNK-3305',
    cameraId: 'CAM-07',
    cameraName: 'Cafeteria',
    timestamp: iso(8, 58, 30),
    confidence: 39.1,
    livenessScore: 74,
    age: 29,
    gender: 'female',
    snapshotTone: 'indigo',
  },
  {
    id: 'UNK-3306',
    cameraId: 'CAM-04',
    cameraName: 'East Stairwell',
    timestamp: iso(8, 44, 12),
    confidence: 47.3,
    livenessScore: 66,
    age: 44,
    gender: 'male',
    snapshotTone: 'orange',
  },
]

// --- Duplicate candidates --------------------------------------------------

export const duplicateCandidates: DuplicateCandidate[] = [
  {
    id: 'DUP-01',
    profileA: { id: 'PRF-1001', name: 'Aria Chen', role: 'employee', avatarTone: 'sky' },
    profileB: { id: 'PRF-1011', name: 'A. Chen (guest)', role: 'visitor', avatarTone: 'cyan' },
    cosineSimilarity: 0.962,
    sharedSightings: 14,
  },
  {
    id: 'DUP-02',
    profileA: { id: 'PRF-1007', name: 'Tomasz Wójcik', role: 'watchlist', avatarTone: 'orange' },
    profileB: { id: 'PRF-1012', name: 'Unknown-4F2', role: 'visitor', avatarTone: 'amber' },
    cosineSimilarity: 0.947,
    sharedSightings: 9,
  },
  {
    id: 'DUP-03',
    profileA: { id: 'PRF-1010', name: 'Elena Rossi', role: 'employee', avatarTone: 'emerald' },
    profileB: { id: 'PRF-1013', name: 'E. Rossi (temp)', role: 'visitor', avatarTone: 'violet' },
    cosineSimilarity: 0.918,
    sharedSightings: 5,
  },
]

// --- Trajectories ----------------------------------------------------------

export const trajectories: SubjectTrajectory[] = [
  {
    profileId: 'PRF-1005',
    profileName: 'Subject 0x8F (BOLO)',
    role: 'blacklist',
    path: [
      { cameraId: 'CAM-05', cameraName: 'Parking Deck', zone: 'Perimeter', timestamp: iso(10, 9, 41), confidence: 82.4, snapshotTone: 'violet' },
      { cameraId: 'CAM-01', cameraName: 'Main Lobby', zone: 'Entrance', timestamp: iso(10, 15, 2), confidence: 91.0, snapshotTone: 'rose' },
      { cameraId: 'CAM-02', cameraName: 'North Corridor', zone: 'Floor 2', timestamp: iso(10, 22, 18), confidence: 88.7, snapshotTone: 'cyan' },
      { cameraId: 'CAM-04', cameraName: 'East Stairwell', zone: 'Floor 3', timestamp: iso(10, 31, 55), confidence: 94.3, snapshotTone: 'amber' },
      { cameraId: 'CAM-03', cameraName: 'Server Room', zone: 'Restricted', timestamp: iso(10, 41, 12), confidence: 97.4, snapshotTone: 'rose' },
    ],
  },
]

// --- Analytics -------------------------------------------------------------

export const footfall: FootfallBucket[] = [
  { hour: '06:00', detections: 42, recognized: 30, unknown: 12 },
  { hour: '07:00', detections: 118, recognized: 96, unknown: 22 },
  { hour: '08:00', detections: 264, recognized: 231, unknown: 33 },
  { hour: '09:00', detections: 389, recognized: 351, unknown: 38 },
  { hour: '10:00', detections: 412, recognized: 372, unknown: 40 },
  { hour: '11:00', detections: 356, recognized: 319, unknown: 37 },
  { hour: '12:00', detections: 401, recognized: 340, unknown: 61 },
  { hour: '13:00', detections: 377, recognized: 322, unknown: 55 },
  { hour: '14:00', detections: 298, recognized: 268, unknown: 30 },
  { hour: '15:00', detections: 244, recognized: 219, unknown: 25 },
  { hour: '16:00', detections: 271, recognized: 240, unknown: 31 },
  { hour: '17:00', detections: 322, recognized: 279, unknown: 43 },
  { hour: '18:00', detections: 189, recognized: 158, unknown: 31 },
  { hour: '19:00', detections: 96, recognized: 74, unknown: 22 },
]

export const ageDistribution: DemographicSlice[] = [
  { label: '0-17', value: 3 },
  { label: '18-25', value: 22 },
  { label: '26-35', value: 38 },
  { label: '36-50', value: 27 },
  { label: '51-65', value: 8 },
  { label: '65+', value: 2 },
]

export const genderDistribution: DemographicSlice[] = [
  { label: 'Male', value: 54 },
  { label: 'Female', value: 43 },
  { label: 'Unknown', value: 3 },
]

export const attendance: AttendanceRecord[] = [
  { profileId: 'PRF-1001', profileName: 'Aria Chen', role: 'employee', department: 'Engineering', checkIn: iso(8, 2), checkOut: iso(17, 41), totalSightings: 34, avatarTone: 'sky' },
  { profileId: 'PRF-1002', profileName: 'Marcus Webb', role: 'employee', department: 'Facilities', checkIn: iso(7, 12), checkOut: iso(16, 3), totalSightings: 41, avatarTone: 'emerald' },
  { profileId: 'PRF-1003', profileName: 'Dr. Lena Ortiz', role: 'vip', department: 'Board', checkIn: iso(9, 40), checkOut: iso(12, 18), totalSightings: 8, avatarTone: 'violet' },
  { profileId: 'PRF-1004', profileName: 'Kofi Mensah', role: 'employee', department: 'Security', checkIn: iso(6, 45), checkOut: iso(18, 55), totalSightings: 52, avatarTone: 'amber' },
  { profileId: 'PRF-1008', profileName: 'Hana Suzuki', role: 'employee', department: 'Design', checkIn: iso(9, 5), checkOut: iso(17, 20), totalSightings: 29, avatarTone: 'indigo' },
  { profileId: 'PRF-1010', profileName: 'Elena Rossi', role: 'employee', department: 'Engineering', checkIn: iso(8, 33), checkOut: iso(18, 2), totalSightings: 37, avatarTone: 'emerald' },
]

// --- Forensic sample matches ----------------------------------------------

export const forensicSampleMatches: ForensicMatch[] = [
  { profileId: 'PRF-1005', profileName: 'Subject 0x8F (BOLO)', role: 'blacklist', cosineSimilarity: 0.941, lastSeen: iso(10, 41, 12), cameraName: 'Main Lobby', avatarTone: 'rose' },
  { profileId: 'PRF-1007', profileName: 'Tomasz Wójcik', role: 'watchlist', cosineSimilarity: 0.883, lastSeen: iso(10, 31, 55), cameraName: 'Main Lobby', avatarTone: 'orange' },
  { profileId: null, profileName: 'Unindexed capture UNK-3302', role: null, cosineSimilarity: 0.804, lastSeen: iso(10, 9, 41), cameraName: 'Parking Deck', avatarTone: 'violet' },
  { profileId: 'PRF-1009', profileName: 'Guest Contractor', role: 'visitor', cosineSimilarity: 0.762, lastSeen: iso(10, 40), cameraName: 'Cafeteria', avatarTone: 'sky' },
]

// --- KPIs & thresholds -----------------------------------------------------

export const systemKpis: SystemKpis = {
  connectedCameras: cameras.filter((c) => c.status !== 'offline').length,
  totalCameras: cameras.length,
  detectionsToday: cameras.reduce((sum, c) => sum + c.detectionsToday, 0),
  activeAlerts: alerts.filter((a) => !a.acknowledged).length,
  systemHealth: 'yellow',
  gpuLoad: 68,
  cpuLoad: 44,
  avgLatencyMs: 58,
}

export const defaultThresholds: ModelThresholds = {
  recognitionConfidence: 82,
  livenessScore: 70,
  unknownFaceRetentionDays: 30,
  autoAlertOnBlacklist: true,
}
